// Map FIFA 3-letter codes to ISO 3166-1 alpha-2 for flagcdn images.
const FIFA_TO_ISO2: Record<string, string> = {
  AFG: "af",
  ALB: "al",
  ALG: "dz",
  AND: "ad",
  ANG: "ao",
  ARG: "ar",
  ARM: "am",
  AUS: "au",
  AUT: "at",
  AZE: "az",
  BAN: "bd",
  BEL: "be",
  BEN: "bj",
  BFA: "bf",
  BHR: "bh",
  BIH: "ba",
  BLR: "by",
  BOL: "bo",
  BOT: "bw",
  BRA: "br",
  BUL: "bg",
  BUR: "bi",
  CAM: "kh",
  CAN: "ca",
  CGO: "cg",
  CHA: "td",
  CHI: "cl",
  CHN: "cn",
  CIV: "ci",
  CMR: "cm",
  COD: "cd",
  COL: "co",
  COM: "km",
  CPV: "cv",
  CRC: "cr",
  CRO: "hr",
  CUB: "cu",
  CUW: "cw",
  CYP: "cy",
  CZE: "cz",
  DEN: "dk",
  DJI: "dj",
  DOM: "do",
  ECU: "ec",
  EGY: "eg",
  ENG: "gb-eng",
  EQG: "gq",
  ERI: "er",
  ESP: "es",
  EST: "ee",
  ETH: "et",
  FIJ: "fj",
  FIN: "fi",
  FRA: "fr",
  FRO: "fo",
  GAB: "ga",
  GAM: "gm",
  GEO: "ge",
  GER: "de",
  GHA: "gh",
  GIB: "gi",
  GNB: "gw",
  GRE: "gr",
  GRN: "gd",
  GUA: "gt",
  GUI: "gn",
  GUY: "gy",
  HAI: "ht",
  HKG: "hk",
  HON: "hn",
  HUN: "hu",
  IDN: "id",
  IND: "in",
  IRL: "ie",
  IRN: "ir",
  IRQ: "iq",
  ISL: "is",
  ISR: "il",
  ITA: "it",
  JAM: "jm",
  JOR: "jo",
  JPN: "jp",
  KAZ: "kz",
  KEN: "ke",
  KGZ: "kg",
  KOR: "kr",
  KOS: "xk",
  KSA: "sa",
  KUW: "kw",
  LAO: "la",
  LAT: "lv",
  LBN: "lb",
  LBR: "lr",
  LBY: "ly",
  LES: "ls",
  LIE: "li",
  LTU: "lt",
  LUX: "lu",
  MAD: "mg",
  MAR: "ma",
  MAS: "my",
  MDA: "md",
  MDV: "mv",
  MEX: "mx",
  MKD: "mk",
  MLI: "ml",
  MLT: "mt",
  MNE: "me",
  MNG: "mn",
  MOZ: "mz",
  MRI: "mu",
  MTN: "mr",
  MWI: "mw",
  MYA: "mm",
  NAM: "na",
  NCA: "ni",
  NED: "nl",
  NEP: "np",
  NGA: "ng",
  NIG: "ne",
  NIR: "gb-nir",
  NOR: "no",
  NZL: "nz",
  OMA: "om",
  PAK: "pk",
  PAN: "pa",
  PAR: "py",
  PER: "pe",
  PHI: "ph",
  PLE: "ps",
  POL: "pl",
  POR: "pt",
  PRK: "kp",
  PUR: "pr",
  QAT: "qa",
  ROU: "ro",
  RSA: "za",
  RUS: "ru",
  RWA: "rw",
  SCO: "gb-sct",
  SDN: "sd",
  SEN: "sn",
  SEY: "sc",
  SIN: "sg",
  SLE: "sl",
  SLV: "sv",
  SMR: "sm",
  SOL: "sb",
  SOM: "so",
  SRB: "rs",
  SRI: "lk",
  SSD: "ss",
  STP: "st",
  SUI: "ch",
  SUR: "sr",
  SVK: "sk",
  SVN: "si",
  SWE: "se",
  SWZ: "sz",
  SYR: "sy",
  TAH: "pf",
  TAN: "tz",
  TGA: "to",
  THA: "th",
  TJK: "tj",
  TKM: "tm",
  TLS: "tl",
  TOG: "tg",
  TPE: "tw",
  TRI: "tt",
  TUN: "tn",
  TUR: "tr",
  UAE: "ae",
  UGA: "ug",
  UKR: "ua",
  URU: "uy",
  USA: "us",
  UZB: "uz",
  VAN: "vu",
  VEN: "ve",
  VIE: "vn",
  WAL: "gb-wls",
  YEM: "ye",
  ZAM: "zm",
  ZIM: "zw",
};

// Full country names for FIFA 3-letter codes. Used in fixture rows and brackets
// so users see "Norway" instead of "NOR".
const FIFA_NAMES: Record<string, string> = {
  AFG: "Afghanistan",
  ALB: "Albania",
  ALG: "Algeria",
  AND: "Andorra",
  ANG: "Angola",
  ARG: "Argentina",
  ARM: "Armenia",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BAN: "Bangladesh",
  BEL: "Belgium",
  BEN: "Benin",
  BFA: "Burkina Faso",
  BHR: "Bahrain",
  BIH: "Bosnia",
  BLR: "Belarus",
  BOL: "Bolivia",
  BOT: "Botswana",
  BRA: "Brazil",
  BUL: "Bulgaria",
  BUR: "Burundi",
  CAM: "Cambodia",
  CAN: "Canada",
  CGO: "Congo",
  CHA: "Chad",
  CHI: "Chile",
  CHN: "China",
  CIV: "Ivory Coast",
  CMR: "Cameroon",
  COD: "DR Congo",
  COL: "Colombia",
  COM: "Comoros",
  CPV: "Cape Verde",
  CRC: "Costa Rica",
  CRO: "Croatia",
  CUB: "Cuba",
  CUW: "Curaçao",
  CYP: "Cyprus",
  CZE: "Czechia",
  DEN: "Denmark",
  DJI: "Djibouti",
  DOM: "Dominican Rep.",
  ECU: "Ecuador",
  EGY: "Egypt",
  ENG: "England",
  EQG: "Eq. Guinea",
  ERI: "Eritrea",
  ESP: "Spain",
  EST: "Estonia",
  ETH: "Ethiopia",
  FIJ: "Fiji",
  FIN: "Finland",
  FRA: "France",
  FRO: "Faroe Is.",
  GAB: "Gabon",
  GAM: "Gambia",
  GEO: "Georgia",
  GER: "Germany",
  GHA: "Ghana",
  GIB: "Gibraltar",
  GNB: "Guinea-Bissau",
  GRE: "Greece",
  GRN: "Grenada",
  GUA: "Guatemala",
  GUI: "Guinea",
  GUY: "Guyana",
  HAI: "Haiti",
  HKG: "Hong Kong",
  HON: "Honduras",
  HUN: "Hungary",
  IDN: "Indonesia",
  IND: "India",
  IRL: "Ireland",
  IRN: "Iran",
  IRQ: "Iraq",
  ISL: "Iceland",
  ISR: "Israel",
  ITA: "Italy",
  JAM: "Jamaica",
  JOR: "Jordan",
  JPN: "Japan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KGZ: "Kyrgyzstan",
  KOR: "South Korea",
  KOS: "Kosovo",
  KSA: "Saudi Arabia",
  KUW: "Kuwait",
  LAO: "Laos",
  LAT: "Latvia",
  LBN: "Lebanon",
  LBR: "Liberia",
  LBY: "Libya",
  LES: "Lesotho",
  LIE: "Liechtenstein",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MAD: "Madagascar",
  MAR: "Morocco",
  MAS: "Malaysia",
  MDA: "Moldova",
  MDV: "Maldives",
  MEX: "Mexico",
  MKD: "N. Macedonia",
  MLI: "Mali",
  MLT: "Malta",
  MNE: "Montenegro",
  MNG: "Mongolia",
  MOZ: "Mozambique",
  MRI: "Mauritius",
  MTN: "Mauritania",
  MWI: "Malawi",
  MYA: "Myanmar",
  NAM: "Namibia",
  NCA: "Nicaragua",
  NED: "Netherlands",
  NEP: "Nepal",
  NGA: "Nigeria",
  NIG: "Niger",
  NIR: "N. Ireland",
  NOR: "Norway",
  NZL: "New Zealand",
  OMA: "Oman",
  PAK: "Pakistan",
  PAN: "Panama",
  PAR: "Paraguay",
  PER: "Peru",
  PHI: "Philippines",
  PLE: "Palestine",
  POL: "Poland",
  POR: "Portugal",
  PRK: "North Korea",
  PUR: "Puerto Rico",
  QAT: "Qatar",
  ROU: "Romania",
  RSA: "South Africa",
  RUS: "Russia",
  RWA: "Rwanda",
  SCO: "Scotland",
  SDN: "Sudan",
  SEN: "Senegal",
  SEY: "Seychelles",
  SIN: "Singapore",
  SLE: "Sierra Leone",
  SLV: "El Salvador",
  SMR: "San Marino",
  SOL: "Solomon Is.",
  SOM: "Somalia",
  SRB: "Serbia",
  SRI: "Sri Lanka",
  SSD: "South Sudan",
  STP: "São Tomé",
  SUI: "Switzerland",
  SUR: "Suriname",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SWE: "Sweden",
  SWZ: "Eswatini",
  SYR: "Syria",
  TAH: "Tahiti",
  TAN: "Tanzania",
  TGA: "Tonga",
  THA: "Thailand",
  TJK: "Tajikistan",
  TKM: "Turkmenistan",
  TLS: "Timor-Leste",
  TOG: "Togo",
  TPE: "Chinese Taipei",
  TRI: "Trinidad",
  TUN: "Tunisia",
  TUR: "Turkey",
  UAE: "UAE",
  UGA: "Uganda",
  UKR: "Ukraine",
  URU: "Uruguay",
  USA: "USA",
  UZB: "Uzbekistan",
  VAN: "Vanuatu",
  VEN: "Venezuela",
  VIE: "Vietnam",
  WAL: "Wales",
  YEM: "Yemen",
  ZAM: "Zambia",
  ZIM: "Zimbabwe",
};

/**
 * Full country name for a FIFA 3-letter code. Falls back to the code itself
 * (or empty string) when unknown.
 */
export function countryName(code?: string | null): string {
  if (!code) return "";
  return FIFA_NAMES[code.toUpperCase()] ?? code;
}

/**
 * Generates a URL for a country's flag image from flagcdn.com.
 * Maps FIFA 3-letter codes to ISO 3166-1 alpha-2 codes.
 */
export function flagUrl(code?: string | null, size: 40 | 80 | 160 | 320 = 80): string | null {
  if (!code) return null;
  const iso = FIFA_TO_ISO2[code.toUpperCase()];
  if (!iso) return null;
  return `https://flagcdn.com/w${size}/${iso}.png`;
}

// Reverse lookup: normalized country name/aliases → FIFA 3-letter code.
// Used when upstream data (e.g. top scorers feed) only carries a team name.
const NAME_TO_FIFA: Record<string, string> = (() => {
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z]/g, "");
  const map: Record<string, string> = {};
  for (const [code, name] of Object.entries(FIFA_NAMES)) map[norm(name)] = code;
  // Common aliases / long-form names not in FIFA_NAMES.
  const aliases: Record<string, string> = {
    southkorea: "KOR",
    republicofkorea: "KOR",
    korearepublic: "KOR",
    northkorea: "PRK",
    koreadpr: "PRK",
    unitedstates: "USA",
    unitedstatesofamerica: "USA",
    us: "USA",
    unitedarabemirates: "UAE",
    ivorycoast: "CIV",
    cotedivoire: "CIV",
    czechrepublic: "CZE",
    bosniaandherzegovina: "BIH",
    bosniaherzegovina: "BIH",
    northmacedonia: "MKD",
    capeverde: "CPV",
    caboverde: "CPV",
    drcongo: "COD",
    democraticrepublicofthecongo: "COD",
    republicofcongo: "CGO",
    dominicanrepublic: "DOM",
    equatorialguinea: "EQG",
    saudiarabia: "KSA",
    newzealand: "NZL",
    southafrica: "RSA",
    trinidadandtobago: "TRI",
    saotomeandprincipe: "STP",
    timorleste: "TLS",
    hongkong: "HKG",
    chinesetaipei: "TPE",
    taiwan: "TPE",
    palestine: "PLE",
    burkinafaso: "BFA",
    sierraleone: "SLE",
    elsalvador: "SLV",
    costarica: "CRC",
    puertorico: "PUR",
    faroeislands: "FRO",
    solomonislands: "SOL",
  };
  for (const [k, v] of Object.entries(aliases)) map[k] = v;
  return map;
})();

/**
 * Resolve a country name (any casing / punctuation) to its FIFA 3-letter code,
 * or null when unknown. Used as a fallback when data lacks a `tla`.
 */
export function fifaCodeFromName(name?: string | null): string | null {
  if (!name) return null;
  const key = name.toLowerCase().replace(/[^a-z]/g, "");
  return NAME_TO_FIFA[key] ?? null;
}

/**
 * Resolves the best-known FIFA code for a team, preferring an explicit code
 * (e.g. a `tla` from a live-scores API) when it's a recognized FIFA code, and
 * falling back to name-based resolution otherwise. Some providers use codes
 * that don't line up with FIFA's 3-letter conventions (e.g. IOC/ISO codes),
 * which otherwise silently drops the crest/flag for that team.
 */
export function bestFifaCode(code?: string | null, name?: string | null): string | null {
  if (code && FIFA_NAMES[code.toUpperCase()]) return code.toUpperCase();
  return fifaCodeFromName(name) ?? (code ? code.toUpperCase() : null);
}

const DHAKA = "Asia/Dhaka";
/**
 * Formats an ISO date string to a human-readable time in Bangladesh Time (Asia/Dhaka).
 * @param iso - The ISO date string.
 * @returns Formatted time string (e.g., "8:00 PM").
 */
export function bdTime(iso: string): string {
  return new Date(iso).toLocaleTimeString("en-US", {
    timeZone: DHAKA,
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });
}
/**
 * Formats an ISO date string to a full date in Bangladesh Time (Asia/Dhaka).
 * @param iso - The ISO date string.
 * @returns Formatted date string (e.g., "Monday, July 12, 2021").
 */
export function bdDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    timeZone: DHAKA,
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}
/**
 * Formats an ISO date string to a short date in Bangladesh Time (Asia/Dhaka).
 * @param iso - The ISO date string.
 * @returns Formatted short date string (e.g., "12 Jul").
 */
export function bdShortDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    timeZone: DHAKA,
    day: "numeric",
    month: "short",
  });
}
