// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdzmbqrbdiwyygxqnepv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkem1icXJiZGl3eXlneHFuZXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMzNDcxMjgsImV4cCI6MjA5ODkyMzEyOH0.P-UOHq2z1-lcu72FVZtf_yI9cz_4_Wd5H5uRqcQflTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});